-- ======================================================
-- Seed: Company Activities (Business Industry)
-- ======================================================

INSERT INTO company_activity (nombre)
VALUES
('AFJP'),
('Administracion'),
('Agro Industrial'),
('Agropecuaria'),
('Alimenticia'),
('Arquitectura'),
('Artesanal'),
('Automotriz'),
('Aerea'),
('Banco / Financiera'),
('Biotecnologia'),
('Call Center'),
('Comercio'),
('Comercio Exterior'),
('Comunicaciones'),
('Construccion'),
('Consultora de RRHH'),
('Consultoria'),
('Consumo Masivo'),
('Correo'),
('Defensa'),
('Diseno'),
('Editorial'),
('Educacion'),
('Energia'),
('Entretenimiento'),
('Farmaceutica'),
('Ferroviaria'),
('Financiera'),
('Forestal'),
('Ganaderia'),
('Gastronomia'),
('Gobierno'),
('Higiene y Perfumeria'),
('Holding'),
('Hoteleria'),
('Imprenta'),
('Industrial'),
('Imprenta e Interpretacion'),
('Informatica / Tecnologias'),
('Informacion e Investigacion'),
('Inmobiliaria'),
('Internet'),
('Juridica'),
('Laboratorio'),
('Manufactura'),
('Medio Ambiente'),
('Medios'),
('Metalmecanica'),
('Mineria / Petroleo / Gas'),
('ONGs'),
('Optica'),
('Otras'),
('Papelera'),
('Pesca'),
('Petroquimica'),
('Plastico'),
('Publicidad / Marketing'),
('Quimica'),
('Retail'),
('Salud'),
('Sector Publico'),
('Seguridad'),
('Seguro'),
('Servicios'),
('Siderurgia'),
('Supermercados / Hipermercados'),
('Tabacalera'),
('Telecomunicaciones'),
('Textil'),
('Transportadora'),
('Transporte'),
('Turismo')

ON CONFLICT (nombre) DO NOTHING;

-- ======================================================
-- Fin seed company activities
-- ======================================================
