version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_2025
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: